server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: remindful
  charset: utf8mb4

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: Remindful
  expiration: 24h

email:
  host: smtp.163.com
  port: 465
  username: cmh22408@163.com
  password: QDTXLMQLCARYHZYS
  from: cmh22408@163.com
  TLS: false
  SSL: true



