server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: remindful
  charset: utf8mb4

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: Remindful
  expiration: 24h


