basePath: /api/v1
definitions:
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.LoginResponse:
    properties:
      expire_at:
        type: string
      token:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - code
    - email
    - password
    - username
    type: object
  model.RegisterResponse:
    properties:
      message:
        type: string
    type: object
  model.SendCodeRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  model.SendCodeResponse:
    properties:
      message:
        type: string
    type: object
  model.User:
    description: 用户信息
    properties:
      created_at:
        description: 创建时间
        type: string
      deleted_at:
        description: 删除时间
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: 用户ID
        type: integer
      is_premium:
        description: 是否是高级用户
        type: boolean
      last_login_at:
        description: 最后登录时间
        type: string
      photo_url:
        description: 头像URL
        type: string
      timezone:
        description: 时区
        type: string
      updated_at:
        description: 更新时间
        type: string
      username:
        description: 用户名
        type: string
    type: object
  model.UserInfoRequest:
    properties:
      email:
        type: string
      photo_url:
        type: string
      username:
        maxLength: 50
        minLength: 2
        type: string
    type: object
  model.UserInfoResponse:
    description: 获取用户信息的响应
    properties:
      message:
        description: 响应信息
        type: string
      user:
        allOf:
        - $ref: '#/definitions/model.User'
        description: 用户信息
    type: object
  response.Response:
    description: 所有接口统一返回的数据结构
    properties:
      code:
        description: 状态码
        example: 200
        type: integer
      data:
        description: 数据
      message:
        description: 提示信息
        example: success
        type: string
    type: object
info:
  contact: {}
  description: ReMindful 后端API文档
  title: ReMindful API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录获取token
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户登录
      tags:
      - 用户
  /register:
    post:
      consumes:
      - application/json
      description: 新用户注册
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册
      tags:
      - 用户
  /send-code:
    post:
      consumes:
      - application/json
      description: 发送邮箱验证码
      parameters:
      - description: 邮箱信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SendCodeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 发送验证码
      tags:
      - 用户
  /user:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserInfoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 获取用户信息
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 更新当前登录用户信息
      parameters:
      - description: 用户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UserInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 更新用户信息
      tags:
      - 用户
swagger: "2.0"
